const PICK_ON = 'PICK ADDRESS';

// Payment Type
const PALPAL = 'PAYPAL';
const POINT = 'POINT';
const VNPAY = 'VNPAY';

// Orders Type
const BUY_POINT = 'BUY_POINT';
const PAYMENT_ORDERS_MERCHANT = 'PAYMENT_ORDERS_MERCHANT';
const PAYMENT_ORDERS_CLIENT = 'PAYMENT_ORDERS_CLIENT';
